/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GridCol {
        /**
          * Number of columns - As it's mobile first, that's the default size.
          * @default 0
         */
        "col": number;
        /**
          * Number of columns - L
          * @default 0
         */
        "colL": number;
        /**
          * Number of columns - M
          * @default 0
         */
        "colM": number;
        /**
          * Number of columns - S
          * @default 0
         */
        "colS": number;
        /**
          * Number of columns - XL
          * @default 0
         */
        "colXL": number;
        /**
          * Is centered
          * @default false
         */
        "isCentered": boolean;
        /**
          * Offset
          * @default 0
         */
        "offset": number;
        /**
          * Offset - L
          * @default 0
         */
        "offsetL": number;
        /**
          * Offset - M
          * @default 0
         */
        "offsetM": number;
        /**
          * Offset right
          * @default 0
         */
        "offsetRight": number;
        /**
          * Offset right - L
          * @default 0
         */
        "offsetRightL": number;
        /**
          * Offset right - M
          * @default 0
         */
        "offsetRightM": number;
        /**
          * Offset right - S
          * @default 0
         */
        "offsetRightS": number;
        /**
          * Offset right - XL
          * @default 0
         */
        "offsetRightXL": number;
        /**
          * Offset - S
          * @default 0
         */
        "offsetS": number;
        /**
          * Offset - XL
          * @default 0
         */
        "offsetXL": number;
    }
    interface GridContainer {
    }
    interface GridGhost {
    }
    interface GridRow {
        /**
          * Align Items
          * @default ''
         */
        "alignItems": string;
        /**
          * Is centered
          * @default false
         */
        "isCentered": boolean;
        /**
          * Is reversed
          * @default false
         */
        "isReversed": boolean;
        /**
          * Is centered on the x axis
          * @default false
         */
        "isXCentered": boolean;
        /**
          * Is centered on the y axis
          * @default false
         */
        "isYCentered": boolean;
        /**
          * Justify content
          * @default ''
         */
        "justifyContent": string;
    }
    interface HrbInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Return the input's current value.
         */
        "getValue": () => Promise<string>;
        /**
          * @default ''
         */
        "idInput": string;
        /**
          * @default ''
         */
        "inputClassnames": string;
        /**
          * Validate the input's current value against its configured constraints.
         */
        "isValid": () => Promise<boolean>;
        "label"?: string;
        /**
          * @default ''
         */
        "labelClassnames": string;
        /**
          * @default 0
         */
        "maxlength": number;
        /**
          * @default ''
         */
        "name": string;
        /**
          * Pattern used by isValid(). String patterns and programmatic RegExp values are supported. String patterns retain the component's historical partial-match validation semantics.
         */
        "pattern"?: string | RegExp;
        "placeholder"?: string;
        /**
          * @default ''
         */
        "prefixInput": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface MyComponent {
        /**
          * The first name.
         */
        "first"?: string;
        /**
          * The last name.
         */
        "last"?: string;
        /**
          * The middle name.
         */
        "middle"?: string;
    }
    interface SimpleButton {
        /**
          * Show the number of clicks.
          * @default false
         */
        "showNbOfClick": boolean;
        /**
          * Visual theme.
          * @default 'primary'
         */
        "theme": 'primary' | 'secondary';
    }
}
export interface HrbInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHrbInputElement;
}
declare global {
    interface HTMLGridColElement extends Components.GridCol, HTMLStencilElement {
    }
    var HTMLGridColElement: {
        prototype: HTMLGridColElement;
        new (): HTMLGridColElement;
    };
    interface HTMLGridContainerElement extends Components.GridContainer, HTMLStencilElement {
    }
    var HTMLGridContainerElement: {
        prototype: HTMLGridContainerElement;
        new (): HTMLGridContainerElement;
    };
    interface HTMLGridGhostElement extends Components.GridGhost, HTMLStencilElement {
    }
    var HTMLGridGhostElement: {
        prototype: HTMLGridGhostElement;
        new (): HTMLGridGhostElement;
    };
    interface HTMLGridRowElement extends Components.GridRow, HTMLStencilElement {
    }
    var HTMLGridRowElement: {
        prototype: HTMLGridRowElement;
        new (): HTMLGridRowElement;
    };
    interface HTMLHrbInputElementEventMap {
        "valueChanges": string;
    }
    interface HTMLHrbInputElement extends Components.HrbInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHrbInputElementEventMap>(type: K, listener: (this: HTMLHrbInputElement, ev: HrbInputCustomEvent<HTMLHrbInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHrbInputElementEventMap>(type: K, listener: (this: HTMLHrbInputElement, ev: HrbInputCustomEvent<HTMLHrbInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHrbInputElement: {
        prototype: HTMLHrbInputElement;
        new (): HTMLHrbInputElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSimpleButtonElement extends Components.SimpleButton, HTMLStencilElement {
    }
    var HTMLSimpleButtonElement: {
        prototype: HTMLSimpleButtonElement;
        new (): HTMLSimpleButtonElement;
    };
    interface HTMLElementTagNameMap {
        "grid-col": HTMLGridColElement;
        "grid-container": HTMLGridContainerElement;
        "grid-ghost": HTMLGridGhostElement;
        "grid-row": HTMLGridRowElement;
        "hrb-input": HTMLHrbInputElement;
        "my-component": HTMLMyComponentElement;
        "simple-button": HTMLSimpleButtonElement;
    }
}
declare namespace LocalJSX {
    interface GridCol {
        /**
          * Number of columns - As it's mobile first, that's the default size.
          * @default 0
         */
        "col"?: number;
        /**
          * Number of columns - L
          * @default 0
         */
        "colL"?: number;
        /**
          * Number of columns - M
          * @default 0
         */
        "colM"?: number;
        /**
          * Number of columns - S
          * @default 0
         */
        "colS"?: number;
        /**
          * Number of columns - XL
          * @default 0
         */
        "colXL"?: number;
        /**
          * Is centered
          * @default false
         */
        "isCentered"?: boolean;
        /**
          * Offset
          * @default 0
         */
        "offset"?: number;
        /**
          * Offset - L
          * @default 0
         */
        "offsetL"?: number;
        /**
          * Offset - M
          * @default 0
         */
        "offsetM"?: number;
        /**
          * Offset right
          * @default 0
         */
        "offsetRight"?: number;
        /**
          * Offset right - L
          * @default 0
         */
        "offsetRightL"?: number;
        /**
          * Offset right - M
          * @default 0
         */
        "offsetRightM"?: number;
        /**
          * Offset right - S
          * @default 0
         */
        "offsetRightS"?: number;
        /**
          * Offset right - XL
          * @default 0
         */
        "offsetRightXL"?: number;
        /**
          * Offset - S
          * @default 0
         */
        "offsetS"?: number;
        /**
          * Offset - XL
          * @default 0
         */
        "offsetXL"?: number;
    }
    interface GridContainer {
    }
    interface GridGhost {
    }
    interface GridRow {
        /**
          * Align Items
          * @default ''
         */
        "alignItems"?: string;
        /**
          * Is centered
          * @default false
         */
        "isCentered"?: boolean;
        /**
          * Is reversed
          * @default false
         */
        "isReversed"?: boolean;
        /**
          * Is centered on the x axis
          * @default false
         */
        "isXCentered"?: boolean;
        /**
          * Is centered on the y axis
          * @default false
         */
        "isYCentered"?: boolean;
        /**
          * Justify content
          * @default ''
         */
        "justifyContent"?: string;
    }
    interface HrbInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "idInput"?: string;
        /**
          * @default ''
         */
        "inputClassnames"?: string;
        "label"?: string;
        /**
          * @default ''
         */
        "labelClassnames"?: string;
        /**
          * @default 0
         */
        "maxlength"?: number;
        /**
          * @default ''
         */
        "name"?: string;
        "onValueChanges"?: (event: HrbInputCustomEvent<string>) => void;
        /**
          * Pattern used by isValid(). String patterns and programmatic RegExp values are supported. String patterns retain the component's historical partial-match validation semantics.
         */
        "pattern"?: string | RegExp;
        "placeholder"?: string;
        /**
          * @default ''
         */
        "prefixInput"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface MyComponent {
        /**
          * The first name.
         */
        "first"?: string;
        /**
          * The last name.
         */
        "last"?: string;
        /**
          * The middle name.
         */
        "middle"?: string;
    }
    interface SimpleButton {
        /**
          * Show the number of clicks.
          * @default false
         */
        "showNbOfClick"?: boolean;
        /**
          * Visual theme.
          * @default 'primary'
         */
        "theme"?: 'primary' | 'secondary';
    }

    interface GridColAttributes {
        "col": number;
        "colS": number;
        "colM": number;
        "colL": number;
        "colXL": number;
        "offset": number;
        "offsetS": number;
        "offsetM": number;
        "offsetL": number;
        "offsetXL": number;
        "offsetRight": number;
        "offsetRightS": number;
        "offsetRightM": number;
        "offsetRightL": number;
        "offsetRightXL": number;
        "isCentered": boolean;
    }
    interface GridRowAttributes {
        "justifyContent": string;
        "alignItems": string;
        "isCentered": boolean;
        "isXCentered": boolean;
        "isYCentered": boolean;
        "isReversed": boolean;
    }
    interface HrbInputAttributes {
        "name": string;
        "prefixInput": string;
        "type": string;
        "required": boolean;
        "readonly": boolean;
        "disabled": boolean;
        "pattern": string | RegExp;
        "maxlength": number;
        "label": string;
        "placeholder": string;
        "labelClassnames": string;
        "inputClassnames": string;
        "idInput": string;
        "value": string;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }
    interface SimpleButtonAttributes {
        "showNbOfClick": boolean;
        "theme": 'primary' | 'secondary';
    }

    interface IntrinsicElements {
        "grid-col": Omit<GridCol, keyof GridColAttributes> & { [K in keyof GridCol & keyof GridColAttributes]?: GridCol[K] } & { [K in keyof GridCol & keyof GridColAttributes as `attr:${K}`]?: GridColAttributes[K] } & { [K in keyof GridCol & keyof GridColAttributes as `prop:${K}`]?: GridCol[K] };
        "grid-container": GridContainer;
        "grid-ghost": GridGhost;
        "grid-row": Omit<GridRow, keyof GridRowAttributes> & { [K in keyof GridRow & keyof GridRowAttributes]?: GridRow[K] } & { [K in keyof GridRow & keyof GridRowAttributes as `attr:${K}`]?: GridRowAttributes[K] } & { [K in keyof GridRow & keyof GridRowAttributes as `prop:${K}`]?: GridRow[K] };
        "hrb-input": Omit<HrbInput, keyof HrbInputAttributes> & { [K in keyof HrbInput & keyof HrbInputAttributes]?: HrbInput[K] } & { [K in keyof HrbInput & keyof HrbInputAttributes as `attr:${K}`]?: HrbInputAttributes[K] } & { [K in keyof HrbInput & keyof HrbInputAttributes as `prop:${K}`]?: HrbInput[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "simple-button": Omit<SimpleButton, keyof SimpleButtonAttributes> & { [K in keyof SimpleButton & keyof SimpleButtonAttributes]?: SimpleButton[K] } & { [K in keyof SimpleButton & keyof SimpleButtonAttributes as `attr:${K}`]?: SimpleButtonAttributes[K] } & { [K in keyof SimpleButton & keyof SimpleButtonAttributes as `prop:${K}`]?: SimpleButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "grid-col": LocalJSX.IntrinsicElements["grid-col"] & JSXBase.HTMLAttributes<HTMLGridColElement>;
            "grid-container": LocalJSX.IntrinsicElements["grid-container"] & JSXBase.HTMLAttributes<HTMLGridContainerElement>;
            "grid-ghost": LocalJSX.IntrinsicElements["grid-ghost"] & JSXBase.HTMLAttributes<HTMLGridGhostElement>;
            "grid-row": LocalJSX.IntrinsicElements["grid-row"] & JSXBase.HTMLAttributes<HTMLGridRowElement>;
            "hrb-input": LocalJSX.IntrinsicElements["hrb-input"] & JSXBase.HTMLAttributes<HTMLHrbInputElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "simple-button": LocalJSX.IntrinsicElements["simple-button"] & JSXBase.HTMLAttributes<HTMLSimpleButtonElement>;
        }
    }
}
